### ISSUE TITLE
Register user via POST to /portal/user do not return diamanteUserId

### ISSUE THREAD

**Issue by alessandro-aglietti** [eltrino/diamantedesk-application#26]
the src/Diamante/FrontBundle/Controller/UserController.php return a generic
`{'success' : true}`

**Comment by odi-um** [comment]
Hi Alessandro,

Could you describe a use case for this ? I'm asking this because `/portal/user` rest resource was designed to work only with portal. In this case user will receive confirmation emails. If you want to create bunch of Diamante Users, its better to use `/api/rest/latest/desk/users` resource (available in master). In this case there will be no confirmation emails. User will be able to log in on fronted immediately. You will get id in response as well.

Thank you.

**Comment by alessandro-aglietti** [comment]
Ok, thank you very much.

I'm using the suggested endpoint.

Regards,
