### ISSUE TITLE
Roadmap: PHP 7 and Symfony 3?

### ISSUE THREAD

**Issue by stephanvierkant** [eltrino/diamantedesk-application#33]
Your website states:
> modern and the most prospective technologies used: PHP 5, Symfony2, OroPlatform, Bootstrap, HTML5, CSS3

The active support period for PHP 5 ends on 1 Jan 2016. While the support fix period has been extended, PHP 5 can't be called 'modern' since the first version of PHP 7 has been around for almost a year.

What's the roadmap for upgrading to Symfony 3 and PHP 7? I know it depends on dependencies such as OroPlatform, but I'd like to know what your plans are.

**Comment by odi-um** [comment]
Hi @stephanvierkant,

At this moment these questions open for us. We are waiting for the final release of Oro Platform v2 to move on. Thus we can't announce the precise date of upgrading DiamanteDesk to PHP7. 
We need to solve two big things/issues
- support of PHP 7
- decoupling of platform bundles

Platform code base size increases dramatically with each new release. New features appear but we actually don't need them and because of tight coupling, it takes too many efforts to exclude them. We don't want to support workarounds in our code base.

Also, you know the situation with the upgrade to Symfony 3.x as in this question we fully depend from Oro Platform. It will appear in our project not earlier than in the platform itself. In any case, we can go with Akeneo PIM approach.

From our point of view, upgrading to latest 1.x version at this moment is a wasting of time.

Thank you.

**Comment by lghamie** [comment]
Any news on supporting PHP 7? Installation seems to download Oro 2.1 which requires php7.
